Allow callers to provide their own Agora SDK and add noop compilation for non-linux machines
membraneframework/membrane_agora_plugin pull request #16
Opened 2024-03-29 23:54 UTC by nickdichev-firework

This PR attempts to solve two problems:

1. Allow callers to provide their own agora sdk and prevent the build from pulling the sdk from agora.
2. Adds a noop build on non-linux machines. The agora sdk is only available on linux. Any project which uses this plugin could not be compiled on mac.

2024-04-02 07:44 UTC, varsill requested changes

2024-04-02 07:44 UTC, varsill commented on c_src/membrane_agora_plugin/noop.cpp
> +ERL_NIF_INIT(niftest,nif_funcs,NULL,NULL,NULL,NULL)
As discussed in the private conversation - the first argument of the `ERL_NIF_INIT` macro defines the Erlang module name that is capable of loading that NIF. We need to define separate NIFs for `Elixir.Membrane.Agora.Sink.Native.Nif` and for `Elixir.Membrane.Agora.Source.Native.Nif`

2024-04-02 07:44 UTC, varsill commented on README.md
It would be good to bump the version from `0.2.1` into `0.2.2` in the README.md as well

2024-04-02 14:30 UTC, varsill commented
I have implemented the requested changes in this PR: https://github.com/nickdichev-firework/membrane_agora_plugin/pull/1

2024-04-03 14:26 UTC, mat-hek approved these changes

2024-04-03 14:34 UTC, varsill approved these changes

2024-04-03 15:35 UTC, merged